## Generated by the script autoignitetnt.sh

execute positioned ~-4 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-4 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-4 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-3 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-3 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-2 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-2 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~-1 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~-1 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~0 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~0 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~1 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~1 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~2 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~2 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~3 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~3 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~-4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~-3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~-2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~-1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~-1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~0 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~0 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~1 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~1 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~2 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~2 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~3 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~3 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

execute positioned ~4 ~4 ~-4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~-3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~-2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~-1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~0 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~1 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~2 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~3 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}
execute positioned ~4 ~4 ~4 if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}

fill ~-4 ~-4 ~-4 ~4 ~4 ~4 air replace tnt
