#! /bin/bash

outfile="autoignitetnt.mcfunction"
echo "## Generated by the script autoignitetnt.sh" > $outfile

range=4

for i in $(seq -$range $range); do 
for j in $(seq -$range $range); do 
  echo "" >> $outfile
  for k in $(seq -$range $range); do 
    echo "execute positioned ~$i ~$j ~$k if block ~ ~ ~ tnt run summon tnt ~ ~ ~ {fuse:80}" >> $outfile 
  done
done
done

echo "" >> $outfile
echo "fill ~-$range ~-$range ~-$range ~$range ~$range ~$range air replace tnt" >> $outfile

